#!/bin/bash

DEB_USER=stomp
LOGDIR=/var/log/go-stomp-nominatim
CONFDIR=/etc/go-stomp-nominatim
UUIDDIR=/var/lib/go-stomp-nominatim

set +e
# Set currect mods
ret=false
getent passwd $DEB_USER >/dev/null 2>&1 && ret=true

if $ret;
then
        chown -R "$DEB_USER:$DEB_USER" $CONFDIR;
        chmod -R u+rX "$CONFDIR"
        
        mkdir "$LOGDIR"; 
        chown -R "$DEB_USER:$DEB_USER" $LOGDIR;
        chmod -R u+rX "$LOGDIR";
       
        mkdir "$UUIDDIR"
        chown -R "$DEB_USER:$DEB_USER" $UUIDDIR;
        chmod -R u+rX "$UUIDDIR";
        
fi

